<a href="https://colab.research.google.com/github/herrynguyen1706/Selecting-the-best-molecular-descriptor/blob/main/Cleaning_Molecular_descriptors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div style="background-color:lightgreen; border-style: dotted;border-color: yellow;text-align:center;color:blue;font-size:20px;border-radius: 50px;padding: 20px 20px;"><strong> Hai Duc Nguyen, PhD in Neuro-pharmacotoxcicology </strong></div>
<div>
my profiles

https://www.researchgate.net/profile/Hai-Nguyen-183

In [11]:
# import session_info
# session_info.show()
# import session_info
# session_info.show()
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/data', force_remount=True)
dataset = pd.read_csv('/content/data/MyDrive/data/decriptorcleanchemo.csv')
dataset.shape

Mounted at /content/data

(172, 680)

In [12]:
dataset.head()

,compounds,Geto,bcutv8,bcutv9,bcutv6,bcutv7,bcutv4,bcutv5,bcutv2,bcutv3,...,E3e,RDFC2,RDFC3,Au,RDFC4,MoRSEP29,Av,MoRSEE14,MoRSEN6,Kv
0,5,2.067,2.649,2.021,2.905,2.873,3.559,3.061,3.802,3.760,...,0.418,-0.084,0.023,94.378,0.269,0.242,68.968,0.274,1.553,0.436
1,6,2.078,2.643,2.047,2.949,2.648,3.172,3.044,3.800,3.715,...,0.334,-0.085,-0.007,81.758,0.380,0.026,58.845,0.682,1.087,0.409
2,8,2.093,2.744,1.963,3.087,3.019,3.588,3.352,3.778,3.754,...,0.308,-3.732,-0.255,137.450,2.843,0.044,111.016,-0.619,1.220,0.194
3,9,2.074,2.767,1.963,3.073,2.924,3.627,3.417,3.783,3.759,...,0.461,-3.329,-0.206,112.247,2.377,0.321,98.297,-0.027,0.835,0.265
4,12,2.014,2.648,2.010,2.856,2.729,3.199,3.083,3.767,3.396,...,0.396,-0.066,-0.035,87.254,0.099,0.271,61.052,0.512,1.295,0.761

In [13]:
descriptors = pd.DataFrame(dataset)
descriptors

,compounds,Geto,bcutv8,bcutv9,bcutv6,bcutv7,bcutv4,bcutv5,bcutv2,bcutv3,...,E3e,RDFC2,RDFC3,Au,RDFC4,MoRSEP29,Av,MoRSEE14,MoRSEN6,Kv
0,5,2.067,2.649,2.021,2.905,2.873,3.559,3.061,3.802,3.760,...,0.418,-0.084,0.023,94.378,0.269,0.242,68.968,0.274,1.553,0.436
1,6,2.078,2.643,2.047,2.949,2.648,3.172,3.044,3.800,3.715,...,0.334,-0.085,-0.007,81.758,0.380,0.026,58.845,0.682,1.087,0.409
2,8,2.093,2.744,1.963,3.087,3.019,3.588,3.352,3.778,3.754,...,0.308,-3.732,-0.255,137.450,2.843,0.044,111.016,-0.619,1.220,0.194
3,9,2.074,2.767,1.963,3.073,2.924,3.627,3.417,3.783,3.759,...,0.461,-3.329,-0.206,112.247,2.377,0.321,98.297,-0.027,0.835,0.265
4,12,2.014,2.648,2.010,2.856,2.729,3.199,3.083,3.767,3.396,...,0.396,-0.066,-0.035,87.254,0.099,0.271,61.052,0.512,1.295,0.761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,314,2.107,2.797,2.107,2.971,2.808,3.405,3.171,3.787,3.589,...,0.340,0.035,-0.028,131.147,0.295,0.447,104.934,-0.220,0.654,0.617
168,316,1.992,1.617,2.084,1.995,1.820,2.760,2.623,3.416,2.841,...,0.159,0.006,0.020,20.843,0.193,0.213,12.166,0.637,0.497,0.689
169,319,2.057,2.765,2.079,2.863,2.797,3.252,2.973,3.520,3.434,...,0.386,0.062,-0.172,69.004,0.500,0.326,52.454,1.351,0.818,0.352
170,320,2.058,2.893,2.102,3.204,3.009,3.392,3.236,3.832,3.795,...,0.451,-0.188,0.230,75.450,0.225,0.163,59.774,1.030,1.319,0.160
171,321,2.034,2.648,1.973,2.919,2.759,3.275,3.079,3.810,3.404,...,0.333,0.035,-0.160,193.774,0.309,0.206,150.892,0.599,0.613,0.633

## 1. Remove highly correlated features

In [14]:
def remove_correlated_features(descriptors):
    # Calculate correlation
    correlated_matrix = descriptors.corr().abs()

    # Upper triangle of correlation matrix
    upper_triangle = correlated_matrix.where(np.triu(np.ones(correlated_matrix.shape),k=1).astype(np.bool))

    # Identify columns that have above 0.9 values of correlation
    to_drop = [column for column in upper_triangle.columns if any(upper_triangle[column] >= 0.9)]
    print(to_drop)
    descriptors_correlated_dropped = descriptors.drop(columns=to_drop, axis=1)
    return descriptors_correlated_dropped

In [15]:
descriptors_new = remove_correlated_features(descriptors)
descriptors_new

['bcutv7', 'bcutv5', 'Platt', 'bcute13', 'Chiv8', 'Chiv5', 'Chiv4', 'Chiv7', 'Chiv6', 'Chiv1', 'Chiv0', 'Chiv3', 'Chiv2', 'bcutm8', 'bcutm7', 'bcutm6', 'bcutm5', 'bcutm4', 'ATSp3', 'ATSp2', 'ATSp1', 'ATSp6', 'ATSp5', 'ATSp4', 'bcutv15', 'bcutv16', 'bcutv12', 'bcutv13', 'PC2', 'PC3', 'PC1', 'PC6', 'PC4', 'PC5', 'Shev', 'MR', 'GMTIV', 'nta', 'MATSe5', 'ZM2', 'ZM1', 'Thara', 'bcutp16', 'bcutp14', 'bcutp15', 'bcutp12', 'bcutp13', 'bcutp10', 'bcute6', 'Tpc', 'ATSm1', 'ATSm2', 'ATSm3', 'ATSm4', 'ATSm5', 'ATSm6', 'kappa1', 'kappa2', 'Hato', 'TPSA', 'IDET', 'SIC4', 'MATSv3', 'SIC6', 'MATSv4', 'W', 'Ipc', 'bcute7', 'bcute5', 'bcute4', 'bcute3', 'bcute2', 'bcute1', 'bcute9', 'bcute8', 'IVDE', 'Xu', 'Smax16', 'DZ', 'DS', 'Chi4pc', 'Pol', 'Chi0', 'Chi6ch', 'Qindex', 'bcutv14', 'bcutv11', 'Chi8', 'Chi9', 'Chi2', 'Chi3', 'Chi1', 'Chi6', 'Chi7', 'Chi4', 'Chi5', 'LogP', 'bcute14', 'bcute12', 'dchi3', 'dchi2', 'dchi1', 'dchi0', 'ATSv1', 'BertzCT', 'S12', 'bcute16', 'bcute15', 'GMTI', 'nring', 'bcute11', 'bcute10', 'CIC5', 'CIC4', 'CIC6', 'CIC1', 'CIC0', 'CIC3', 'CIC2', 'bcutp8', 'bcutp9', 'bcutp4', 'bcutp5', 'bcutp6', 'bcutp7', 'bcutp1', 'bcutp2', 'bcutp3', 'ncarb', 'kappam1', 'TIAC', 'kappam3', 'kappam2', 'phi', 'GATSv5', 'GATSv4', 'Chiv10', 'slogPVSA5', 'Gravto', 'Sitov', 'LabuteASA', 'radiust', 'MATSp5', 'MATSp4', 'MATSp1', 'nhev', 'Hy', 'knotpv', 'Weight', 'UI', 'ATSv3', 'ATSv2', 'ATSv5', 'ATSv4', 'ATSv7', 'ATSv6', 'diametert', 'Scar', 'ISIZ', 'Tnc', 'Tigdi', 'ATSe1', 'ATSe2', 'ATSe3', 'ATSe4', 'ATSe5', 'ATSe6', 'Hatov', 'Mac', 'Arto', 'IC5', 'IC4', 'Tsch', 'AW', 'MZM2', 'MZM1', 'Sito', 'Chi10', 'bcutm16', 'bcutm15', 'bcutm14', 'bcutm13', 'bcutm12', 'bcutm11', 'bcutm10', 'RDFV1', 'RDFU9', 'RDFU2', 'RDFU1', 'RDFU4', 'Harary3D', 'MoRSEM4', 'MoRSEV19', 'MoRSEV17', 'RDFE8', 'RDFE9', 'RDFE2', 'RDFE3', 'RDFE1', 'RDFE6', 'RDFE7', 'RDFE4', 'RDFE5', 'WNSA2', 'RDFP15', 'RDFP14', 'RDFP11', 'RDFP10', 'RDFP13', 'RDFP12', 'MoRSEM19', 'MoRSEM10', 'MoRSEM14', 'MoRSEM17', 'MoRSEU30', 'L1u', 'L1v', 'L1p', 'RDFP5', 'RDFP4', 'RDFP7', 'RDFP6', 'RDFP1', 'RDFP3', 'RDFP2', 'L1e', 'RDFP9', 'RDFP8', 'L1m', 'P1m', 'P1p', 'P1u', 'P1v', 'RDFE14', 'RDFE15', 'RDFE11', 'PPSA2', 'MoRSEP11', 'MoRSEP12', 'E2p', 'MoRSEP17', 'DPSA1', 'MoRSEN5', 'MoRSEN4', 'MoRSEN3', 'MoRSEN2', 'MoRSEN1', 'E2e', 'L3v', 'L3u', 'L3p', 'MoRSEN16', 'MoRSEN17', 'W3DH', 'RDFU11', 'RDFM2', 'FNSA1', 'P2p', 'RDFV4', 'MoRSEN22', 'MoRSEN23', 'RDFV15', 'RDFV14', 'RDFV13', 'RDFV12', 'RDFV11', 'RDFM9', 'MoRSEN25', 'RDFV9', 'MoRSEE6', 'MoRSEE4', 'RDFV8', 'MoRSEE2', 'Ve', 'RDFE10', 'Vm', 'Vp', 'MoRSEV18', 'Vu', 'Vv', 'RDFE13', 'RDFU13', 'MoRSEP10', 'MoRSEP13', 'MoRSEP15', 'MoRSEP14', 'WPSA2', 'MoRSEN9', 'MoRSEU8', 'MoRSEU9', 'MoRSEU6', 'MoRSEU4', 'MoRSEU3', 'MoRSEP19', 'MoRSEP18', 'DPSA3', 'RDFV7', 'RDFV5', 'DPSA2', 'RDFV3', 'RDFV2', 'RDFM4', 'WPSA3', 'AGDD', 'MoRSEC1', 'MoRSEC2', 'MoRSEC3', 'MoRSEC5', 'MoRSEC7', 'WPSA1', 'MoRSEE20', 'MoRSEE24', 'RDFE12', 'RDFV10', 'Ae', 'MoRSEV26', 'MoRSEV27', 'MoRSEV24', 'MoRSEV22', 'MoRSEV23', 'MoRSEV20', 'P2e', 'P2m', 'MoRSEC18', 'P2u', 'P2v', 'MoRSEP1', 'grav', 'MoRSEV6', 'MoRSEN20', 'L2e', 'MoRSEV5', 'MoRSEM27', 'rygr', 'MoRSEE7', 'MoRSEE5', 'ASA', 'MoRSEV3', 'MoRSEE1', 'Ke', 'E3p', 'RDFV6', 'Km', 'MoRSEV7', 'RDFM1', 'Kp', 'Ku', 'MoRSEV2', 'MoRSEP4', 'RDFM13', 'MoRSEN13', 'MoRSEM20', 'MoRSEN11', 'MoRSEV4', 'SPAN', 'MoRSEM24', 'MoRSEN15', 'MoRSEN14', 'MoRSEM29', 'MoRSEM28', 'MoRSEN19', 'MoRSEN18', 'L2m', 'MoRSEV8', 'MoRSEU29', 'MoRSEU28', 'L2u', 'MoRSEV1', 'MoRSEN12', 'L2v', 'MoRSEU21', 'MoRSEU20', 'MoRSEU23', 'MoRSEU22', 'MoRSEU25', 'MoRSEU24', 'MoRSEU27', 'MoRSEV25', 'Tv', 'Am', 'SEig', 'Tu', 'Tp', 'Tm', 'RDFU12', 'PNSA3', 'PNSA2', 'PNSA1', 'Te', 'MSA', 'MoRSEE22', 'Ap', 'MoRSEE10', 'MoRSEE11', 'MoRSEE12', 'MoRSEE13', 'MoRSEP9', 'MoRSEE15', 'MoRSEE16', 'MoRSEE17', 'MoRSEE18', 'MoRSEE19', 'Du', 'Dp', 'MoRSEN8', 'E1v', 'MoRSEM21', 'RNCS', 'MoRSEP28', 'MoRSEN30', 'E1e', 'MoRSEN7', 'W3D', 'RDFU14', 'RDFU15', 'MoRSEV30', 'RDFU10', 'E3e', 'RDFC2', 'Au', 'RDFC4', 'MoRSEP29', 'Av', 'MoRSEE14', 'MoRSEN6', 'Kv']

<ipython-input-14-eb8fd350a939>:6: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  upper_triangle = correlated_matrix.where(np.triu(np.ones(correlated_matrix.shape),k=1).astype(np.bool))

,compounds,Geto,bcutv8,bcutv9,bcutv6,bcutv4,bcutv2,bcutv3,bcutv1,SPP,...,E3m,MoRSEV9,RDFC1,De,MoRSEC12,E1p,E1u,E1m,RDFC9,RDFC3
0,5,2.067,2.649,2.021,2.905,3.559,3.802,3.760,3.992,0.833,...,0.157,0.449,-0.171,1.215,-0.035,0.431,0.499,0.341,0.236,0.023
1,6,2.078,2.643,2.047,2.949,3.172,3.800,3.715,4.058,0.563,...,0.064,0.447,-0.071,1.203,-0.042,0.421,0.438,0.442,0.016,-0.007
2,8,2.093,2.744,1.963,3.087,3.588,3.778,3.754,3.966,0.646,...,0.187,0.254,-0.169,1.066,-0.185,0.322,0.442,0.240,-0.161,-0.255
3,9,2.074,2.767,1.963,3.073,3.627,3.783,3.759,3.974,0.538,...,0.288,0.429,-0.229,1.413,-0.169,0.445,0.463,0.528,1.437,-0.206
4,12,2.014,2.648,2.010,2.856,3.199,3.767,3.396,4.024,0.800,...,0.108,0.572,-0.079,1.309,-0.034,0.384,0.474,0.505,0.029,-0.035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,314,2.107,2.797,2.107,2.971,3.405,3.787,3.589,4.004,0.549,...,0.257,0.961,-0.175,1.225,-0.053,0.460,0.502,0.356,0.256,-0.028
168,316,1.992,1.617,2.084,1.995,2.760,3.416,2.841,3.940,0.555,...,0.004,0.105,-0.171,1.262,-0.009,0.425,0.619,0.285,-0.031,0.020
169,319,2.057,2.765,2.079,2.863,3.252,3.520,3.434,3.979,0.690,...,0.164,-0.022,-0.129,1.167,-0.040,0.347,0.420,0.387,-0.177,-0.172
170,320,2.058,2.893,2.102,3.204,3.392,3.832,3.795,4.024,0.589,...,0.267,0.249,-0.417,1.196,-0.005,0.273,0.360,0.709,0.020,0.230
171,321,2.034,2.648,1.973,2.919,3.275,3.810,3.404,3.853,0.635,...,0.131,0.028,-0.327,1.538,-0.089,0.550,0.658,0.375,0.181,-0.160

**2. Remove descriptors with low variance**

In [9]:
# credit to dataprofessor
# adapted from:https://github.com/dataprofessor/padel/blob/main/padelpy.ipynb

from sklearn.feature_selection import VarianceThreshold

def remove_low_variance(input_data, threshold=0.1):
    selection = VarianceThreshold(threshold)
    selection.fit(input_data)
    return input_data[input_data.columns[selection.get_support(indices=True)]]

X = remove_low_variance(descriptors_new, threshold=0.1)
X

,compounds,bcutv8,Tac,Chiv9,Smin,bcutm2,bcutm1,TPSA1,Shet,naro,...,RDFM5,MoRSEP20,MoRSEP24,MoRSEE21,MoRSEE25,MoRSEE26,MoRSEP7,RPCS,MoRSEP2,MoRSEV9
0,5,2.649,4.557,0.315,-1.240,3.803,4.071,72.19,41.426,23.0,...,3.926,-0.802,1.174,0.081,-0.865,-0.233,-1.577,427.634,-2.484,0.449
1,6,2.643,3.436,0.380,-0.238,3.892,4.247,52.71,29.724,22.0,...,2.784,-0.220,0.867,-0.453,-0.266,-0.467,-1.681,12.247,-2.490,0.447
2,8,2.744,4.338,0.849,-3.465,4.177,4.426,53.35,30.726,22.0,...,6.860,-0.366,0.948,-0.180,-0.099,-0.676,-1.718,55.904,-3.739,0.254
3,9,2.767,3.826,0.951,-2.981,4.178,4.434,44.12,31.734,22.0,...,5.789,-0.334,1.125,-0.139,-0.214,-0.739,-1.926,58.490,-3.191,0.429
4,12,2.648,4.198,0.298,-0.426,3.803,4.108,87.26,45.009,16.0,...,2.441,-0.750,0.696,-0.032,-0.626,-0.453,-0.841,154.069,-2.042,0.572
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,314,2.797,4.060,0.358,0.401,3.951,4.048,52.55,29.073,17.0,...,12.160,-0.829,0.980,-0.087,-0.501,-0.488,-0.681,456.551,-3.204,0.961
168,316,1.617,2.037,0.047,0.727,3.450,4.008,51.80,14.436,11.0,...,0.576,-0.370,0.379,0.102,-0.337,-0.116,-0.303,130.990,-0.987,0.105
169,319,2.765,4.810,0.196,0.379,3.831,4.073,71.01,38.837,11.0,...,9.164,-0.642,0.456,-0.180,-0.259,-0.344,-0.234,1.460,-1.768,-0.022
170,320,2.893,5.538,0.289,-0.291,3.874,4.065,82.26,47.205,23.0,...,21.119,-0.784,0.171,-0.409,0.305,-0.489,-2.209,19.392,-2.566,0.249
171,321,2.648,4.813,0.311,-0.301,3.849,4.087,103.90,36.853,12.0,...,17.549,-0.677,0.835,0.065,-0.773,0.108,-0.894,26.662,-2.796,0.028

In [10]:
# export data
d=pd.DataFrame(X)
d.to_excel(excel_writer=r'/content/data/MyDrive/data/descriptorcleanchemopy.xlsx')